In [1]:
import numpy as np
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.utils import np_utils
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

Using TensorFlow backend.


In [2]:
seed=7
np.random.seed(seed)


In [3]:
dataframe=pandas.read_csv("iris.data",header=None)
dataset=dataframe.values

x=dataset[:,0:4].astype(float)
y=dataset[:,4]
print(y.shape)


(150,)


In [9]:
encoder=LabelEncoder()
encoder.fit(y)
yenc=encoder.transform(y)
dummy_y=np_utils.to_categorical(yenc)
print(yenc)
print(dummy_y)
#print(x)

[2 2 2 1 1 2 0 0 2 2 0 0 0 1 1 0 0 1 1 0 1 1 2 1 2 1 0 1 2 0 0 2 1 0 0 0 2
 2 1 0 0 0 2 0 1 2 0 1 2 1 2 1 2 1 1 1 0 2 1 2 2 1 0 2 1 1 1 1 2 0 2 0 0 0
 2 2 0 2 1 1 2 1 1 1 1 0 0 2 2 2 0 1 2 0 2 0 2 2 1 0 2 2 2 0 2 1 0 1 2 0 1
 0 2 0 2 1 0 2 2 0 0 1 2 0 0 0 0 1 0 0 1 1 1 2 1 2 0 1 1 1 0 2 2 0 0 1 1 2
 2 1]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.

In [5]:
def build_model():
    model = Sequential()
    model.add(Dense(8, activation='relu', input_shape=(4,)))
    model.add(Dense(3, activation='softmax'))
    model.compile(optimizer='Adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])
    return model
estimator=KerasClassifier(build_fn=build_model,epochs=200,batch_size=5,verbose=0)
kfold=KFold(n_splits=10,shuffle=True,random_state=seed)
results=cross_val_score(estimator,x,dummy_y,cv=kfold)
print("Baseline:%.2f%%(%.2f%%)"%(results.mean()*100,results.std()*100))



Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Baseline:97.33%(4.42%)


# SMALLER MODEL


In [ ]:
def build_model():
    model = Sequential()
    model.add(Dense(1, activation='relu', input_shape=(4,)))
    model.add(Dense(3, activation='softmax'))
    model.compile(optimizer='Adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])
    return model
estimator=KerasClassifier(build_fn=build_model,epochs=200,batch_size=5,verbose=0)
kfold=KFold(n_splits=10,shuffle=True,random_state=seed)
results=cross_val_score(estimator,x,dummy_y,cv=kfold)
print("Baseline:%.2f%%(%.2f%%)"%(results.mean()*100,results.std()*100))

# LARGER MODEL

In [ ]:
def build_model():
    model = Sequential()
    model.add(Dense(90, activation='relu', input_shape=(4,)))
    model.add(Dense(87, activation='relu'))
    model.add(Dense(207, activation='relu'))
    model.add(Dense(3, activation='softmax'))
    model.compile(optimizer='Adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])
    return model
estimator=KerasClassifier(build_fn=build_model,epochs=200,batch_size=5,verbose=0)
kfold=KFold(n_splits=10,shuffle=True,random_state=seed)
results=cross_val_score(estimator,x,dummy_y,cv=kfold)
print("Baseline:%.2f%%(%.2f%%)"%(results.mean()*100,results.std()*100))

# OVERFITTING MODEL


In [ ]:
def build_model():
    model = Sequential()
    model.add(Dense(90, activation='relu', input_shape=(4,)))
    model.add(Dense(87, activation='relu'))
    model.add(Dense(207, activation='relu')) 
    model.add(Dense(3, activation='softmax'))
    model.compile(optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy'])
    return model
estimator=KerasClassifier(build_fn=build_model,epochs=700,batch_size=5,verbose=0)
kfold=KFold(n_splits=10,shuffle=True,random_state=seed)
results=cross_val_score(estimator,x,dummy_y,cv=kfold)
print("Baseline:%.2f%%(%.2f%%)"%(results.mean()*100,results.std()*100))

# TUNING THE MODEL

In [ ]:
def build_model():
    model = Sequential()
    model.add(Dense(90, activation='relu', input_shape=(4,)))
    model.add(Dense(87, activation='relu'))
    model.add(Dense(207, activation='relu'))
    model.add(Dense(3, activation='softmax'))
    model.compile(optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['acc'])
    return model
estimator=KerasClassifier(build_fn=build_model,epochs=200,batch_size=5,verbose=0)
kfold=KFold(n_splits=10,shuffle=True,random_state=seed)
results=cross_val_score(estimator,x,dummy_y,cv=kfold)
print("Baseline:%.2f%%(%.2f%%)"%(results.mean()*100,results.std()*100))
def build_model():
    model = Sequential()
    model.add(Dense(90, activation='relu', input_shape=(4,)))
    model.add(Dense(87, activation='relu'))
    model.add(Dense(207, activation='relu'))
    model.add(Dense(3, activation='softmax'))
    model.compile(optimizer='rmsprop',
    loss='mse',
    metrics=['acc'])
    return model
estimator=KerasClassifier(build_fn=build_model,epochs=200,batch_size=5,verbose=0)
kfold=KFold(n_splits=10,shuffle=True,random_state=seed)
results=cross_val_score(estimator,x,dummy_y,cv=kfold)
print("Baseline:%.2f%%(%.2f%%)"%(results.mean()*100,results.std()*100))
def build_model():
    model = Sequential()
    model.add(Dense(90, activation='relu', input_shape=(4,)))
    model.add(Dense(87, activation='tanh'))
    model.add(Dense(207, activation='tanh'))
    model.add(Dense(3, activation='softmax'))
    model.compile(optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['acc'])
    return model
estimator=KerasClassifier(build_fn=build_model,epochs=200,batch_size=5,verbose=0)
kfold=KFold(n_splits=10,shuffle=True,random_state=seed)
results=cross_val_score(estimator,x,dummy_y,cv=kfold)
print("Baseline:%.2f%%(%.2f%%)"%(results.mean()*100,results.std()*100))

# Functional API

In [6]:
from keras.models import Model
from keras.layers import Input, Dense
def build_model():
    input_tensor = Input(shape=(4,))
    x = Dense(8, activation='relu')(input_tensor)
    x = Dense(3, activation='relu')(x)
    output_tensor = Dense(3, activation='softmax')(x)
    model = Model(input_tensor, output_tensor)
    model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model
estimator= KerasClassifier(build_fn=build_model,epochs=100,batch_size=5,verbose=0)
kfold=KFold(n_splits=10,shuffle=True,random_state=seed)
results=cross_val_score(estimator,x,dummy_y,cv=kfold)
print("Results:%.2f%%(%.2f%%)"%(results.mean()*100,results.std()*100))

Results:72.00%(29.48%)


# WITH KERAS

In [7]:
from numpy import argmax
np.random.shuffle(dataset)
np.random.shuffle(y)
np.random.shuffle(x)
data = y
print(data)
flower = 'Iris-setosa', 'Iris-versicolor','Iris-virginica'

char_to_int = dict((c, i) for i, c in enumerate(flower))


y = [char_to_int[char] for char in data]
print(y)



['Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Ir

In [8]:
def build_model():
    model = Sequential()
    model.add(Dense(8, activation='relu', input_shape=(4,)))
    model.add(Dense(3, activation='softmax'))
    model.compile(optimizer='Adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])
    return model

In [ ]:
train_dataset = x[:100]
test_dataset = x[100:]
train_label = dummy_y[:100]
test_label = dummy_y[100:]
k=4
num_val_samples = len(train_dataset) // k
num_epochs = 200

for i in range(k):
  print('processing fold #', i)
  val_data = train_dataset[i * num_val_samples: (i + 1) * num_val_samples]
  val_labels = train_label[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate(
      [train_dataset[:i * num_val_samples],train_dataset[(i + 1) * num_val_samples:]],axis=0)
  partial_train_labels = np.concatenate(
      [train_label[:i * num_val_samples],
       train_label[(i + 1) * num_val_samples:]])
  model = build_model()
  model.fit(partial_train_data, partial_train_labels , validation_data=(val_data, val_labels), epochs=num_epochs, batch_size=1, verbose=0)
  loss , acc = model.evaluate(val_data, val_labels , verbose=0)
  print(acc)
#model.train(xtrain)

processing fold # 0
0.4399999976158142
processing fold # 1
0.20000000298023224
processing fold # 2
0.5600000023841858
processing fold # 3


In [ ]:

ytrain=y[:100]
k=4

#print(num_val_samples)
num_epochs = 100
all_mae_histories = []
for i in range(k):
    num_val_samples = len(xtrain)
    num_
    print('processing fold #', i)
    val_data = xtrain[i * (num_val_samples//k): (i + 1) * (num_val_samples//k)]

    val_targets = ytrain[i * (num_val_samples//k): (i + 1) * (num_val_samples//k)]
    partial_train_data = np.concatenate(
    [xtrain[:i * num_val_samples],
    xtrain[(i + 1) * num_val_samples:]],
    axis=0)
    partial_train_targets = np.concatenate(
    [ytrain[:i * num_val_samples],
    ytrain[(i + 1) * num_val_samples:]],
    axis=0)




#model = build_model()
#model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=5,verbose=0)
#results = model.evaluate(xtrain,ytrain)


In [ ]:
def build_model():
    
    model = Sequential()
    model.add(Dense(8, activation='relu',  input_shape=(4,)))
    model.add(Dense(1, activation='softmax')  )    
    from keras import optimizers
    model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
    return model
model=build_model()
model.fit(x[100:], y[100:], epochs=60, batch_size=5)
results = model.evaluate(x[100:], y[100:])